import { useState, useEffect } from "react";
import jsPDF from "jspdf";

const SECTIONS = [
  { key: "diagnosis", label: "Diagnosis" },
  { key: "investigations", label: "Investigations" },
  { key: "management", label: "Management in ED" },
  { key: "plan", label: "Plan / Disposition" },
  { key: "followUp", label: "Follow-up" },
  { key: "gpLetter", label: "GP letter (paragraph)" },
];

function DischargeSummaryModal({
  patient,
  initialSummary,
  source,
  error,
  onCancel,
  onConfirmDischarge,
}) {
  const initial = initialSummary || {};
  const [fields, setFields] = useState(() => ({
    diagnosis: initial.diagnosis || "",
    investigations: initial.investigations || "",
    management: initial.management || "",
    plan: initial.plan || "",
    followUp: initial.followUp || "",
    gpLetter: initial.gpLetter || "",
  }));
  const [copied, setCopied] = useState(false);

  // Reset if a new initialSummary is provided
  useEffect(() => {
    setFields({
      diagnosis: initial.diagnosis || "",
      investigations: initial.investigations || "",
      management: initial.management || "",
      plan: initial.plan || "",
      followUp: initial.followUp || "",
      gpLetter: initial.gpLetter || "",
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialSummary]);

  const updateField = (key, value) => {
    setFields((f) => ({ ...f, [key]: value }));
  };

  const buildPlainText = () => {
    const today = new Date().toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
    return `ED DISCHARGE SUMMARY
${"=".repeat(50)}

Patient:           ${patient.name || "Unknown"}
Patient ID:        ${patient.patientId || "—"}
Presenting:        ${patient.presentingComplaint || "—"}
Time in dept:      ${patient.timeInDept || "—"}
Discharge date:    ${today}

${"=".repeat(50)}

DIAGNOSIS
${fields.diagnosis}

INVESTIGATIONS
${fields.investigations}

MANAGEMENT IN ED
${fields.management}

PLAN / DISPOSITION
${fields.plan}

FOLLOW-UP
${fields.followUp}

${"=".repeat(50)}

GP LETTER
${fields.gpLetter}

${"=".repeat(50)}
Generated by ED Tracker — please verify before clinical use.
`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildPlainText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Copy failed:", err);
      alert("Couldn't copy to clipboard. Browser may have blocked it.");
    }
  };

  const handleDownloadPdf = () => {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 48;
    const usableWidth = pageWidth - margin * 2;
    let y = margin;

    const writeHeading = (text, fontSize = 14) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(fontSize);
      doc.text(text, margin, y);
      y += fontSize + 6;
    };

    const writeBody = (text, fontSize = 11) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(fontSize);
      const lines = doc.splitTextToSize(text || "—", usableWidth);
      lines.forEach((line) => {
        if (y > 780) {
          doc.addPage();
          y = margin;
        }
        doc.text(line, margin, y);
        y += fontSize + 4;
      });
      y += 6;
    };

    const writeMeta = (label, value) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(label, margin, y);
      doc.setFont("helvetica", "normal");
      doc.text(value || "—", margin + 110, y);
      y += 14;
    };

    // Header
    writeHeading("ED Discharge Summary", 18);
    y += 4;

    const today = new Date().toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
    writeMeta("Patient:", patient.name || "Unknown");
    writeMeta("Patient ID:", patient.patientId || "—");
    writeMeta("Presenting complaint:", patient.presentingComplaint || "—");
    writeMeta("Time in dept:", patient.timeInDept || "—");
    writeMeta("Discharge date:", today);
    y += 8;

    // Sections
    SECTIONS.forEach(({ key, label }) => {
      writeHeading(label.toUpperCase(), 11);
      writeBody(fields[key]);
    });

    // Footer
    if (y > 760) {
      doc.addPage();
      y = margin;
    }
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      "Generated by ED Tracker — please verify before clinical use.",
      margin,
      820
    );

    const filename = `discharge-${(patient.name || "patient")
      .replace(/\s+/g, "-")
      .toLowerCase()}.pdf`;
    doc.save(filename);
  };

  return (
    <div className="modal-backdrop" onClick={onCancel}>
      <div
        className="modal-card modal-card-wide"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="detail-header">
          <h2>Discharge summary — {patient.name}</h2>
          <button onClick={onCancel}>Close</button>
        </div>

        {source === "claude" && (
          <div className="ai-badge ai-badge-success">
            ✨ Drafted by Claude — please review and edit before issuing
          </div>
        )}
        {source === "fallback" && (
          <div className="ai-badge ai-badge-warn">
            ⚠️ AI summary unavailable
            {error ? `: ${error}` : ""}. Fields show a best-effort
            structured copy of the record — review and complete manually.
          </div>
        )}

        <div className="discharge-grid">
          {SECTIONS.map(({ key, label }) => (
            <label key={key} className="discharge-field">
              <span className="discharge-field-label">{label}</span>
              <textarea
                value={fields[key]}
                onChange={(e) => updateField(key, e.target.value)}
                rows={key === "gpLetter" ? 6 : 4}
              />
            </label>
          ))}
        </div>

        <div className="discharge-actions">
          <button className="ghost-btn-dark" onClick={handleCopy}>
            {copied ? "Copied ✓" : "Copy as text"}
          </button>
          <button className="ghost-btn-dark" onClick={handleDownloadPdf}>
            Download PDF
          </button>
          <div style={{ flex: 1 }} />
          <button className="ghost-btn-dark" onClick={onCancel}>
            Cancel
          </button>
          <button
            className="primary-btn"
            onClick={() => onConfirmDischarge(fields)}
          >
            Confirm discharge
          </button>
        </div>
      </div>
    </div>
  );
}

export default DischargeSummaryModal;